
package com.example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param intB
     * @param intA
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "value", targetNamespace = "")
    @RequestWrapper(localName = "subtract", targetNamespace = "http://example.com/", className = "com.example.Subtract")
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://example.com/", className = "com.example.SubtractResponse")
    @Action(input = "http://example.com/Calculator/subtractRequest", output = "http://example.com/Calculator/subtractResponse")
    public int subtract(
        @WebParam(name = "intA", targetNamespace = "")
        int intA,
        @WebParam(name = "intB", targetNamespace = "")
        int intB);

    /**
     * 
     * @param intB
     * @param intA
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "value", targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://example.com/", className = "com.example.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://example.com/", className = "com.example.MultiplyResponse")
    @Action(input = "http://example.com/Calculator/multiplyRequest", output = "http://example.com/Calculator/multiplyResponse")
    public int multiply(
        @WebParam(name = "intA", targetNamespace = "")
        int intA,
        @WebParam(name = "intB", targetNamespace = "")
        int intB);

    /**
     * 
     * @param intB
     * @param intA
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "value", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://example.com/", className = "com.example.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://example.com/", className = "com.example.AddResponse")
    @Action(input = "http://example.com/Calculator/addRequest", output = "http://example.com/Calculator/addResponse")
    public int add(
        @WebParam(name = "intA", targetNamespace = "")
        int intA,
        @WebParam(name = "intB", targetNamespace = "")
        int intB);

    /**
     * 
     * @param intB
     * @param intA
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "value", targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://example.com/", className = "com.example.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://example.com/", className = "com.example.DivideResponse")
    @Action(input = "http://example.com/Calculator/divideRequest", output = "http://example.com/Calculator/divideResponse")
    public int divide(
        @WebParam(name = "intA", targetNamespace = "")
        int intA,
        @WebParam(name = "intB", targetNamespace = "")
        int intB);

}
